#ifndef PORT_MAP_H
#define PORT_MAP_H

#define PORT_PIN_CONSTANT(_PORT_, _OFFSET_) (_PORT_ & (1 << _OFFSET_))

#define PORT_DPIN_22 PORT_PIN_CONSTANT(PINA, 0) // Mxz0
#define PORT_DPIN_23 PORT_PIN_CONSTANT(PINA, 1) // Mxz1
#define PORT_DPIN_24 PORT_PIN_CONSTANT(PINA, 2) // Mxz2
#define PORT_DPIN_25 PORT_PIN_CONSTANT(PINA, 3) // Mxz3
#define PORT_DPIN_26 PORT_PIN_CONSTANT(PINA, 4) // Mxz4
#define PORT_DPIN_27 PORT_PIN_CONSTANT(PINA, 5) // Mxz5
#define PORT_DPIN_28 PORT_PIN_CONSTANT(PINA, 6) // Mxz6
#define PORT_DPIN_29 PORT_PIN_CONSTANT(PINA, 7) // Mxz7

#define PORT_DPIN_53 PORT_PIN_CONSTANT(PINB, 0) // MxS2
#define PORT_DPIN_52 PORT_PIN_CONSTANT(PINB, 1) // MxS1
#define PORT_DPIN_51 PORT_PIN_CONSTANT(PINB, 2) // MxS0
#define PORT_DPIN_50 PORT_PIN_CONSTANT(PINB, 3) // Arp S1
#define PORT_DPIN_10 PORT_PIN_CONSTANT(PINB, 4) // NONE
#define PORT_DPIN_11 PORT_PIN_CONSTANT(PINB, 5) // NONE
#define PORT_DPIN_12 PORT_PIN_CONSTANT(PINB, 6) // NONE
#define PORT_DPIN_13 PORT_PIN_CONSTANT(PINB, 7) // NONE

#define PORT_DPIN_37 PORT_PIN_CONSTANT(PINC, 0) // NONE
#define PORT_DPIN_36 PORT_PIN_CONSTANT(PINC, 1) // NONE
#define PORT_DPIN_35 PORT_PIN_CONSTANT(PINC, 2) // Mxz13
#define PORT_DPIN_34 PORT_PIN_CONSTANT(PINC, 3) // Mxz12
#define PORT_DPIN_33 PORT_PIN_CONSTANT(PINC, 4) // Mxz11
#define PORT_DPIN_32 PORT_PIN_CONSTANT(PINC, 5) // Mxz10
#define PORT_DPIN_31 PORT_PIN_CONSTANT(PINC, 6) // Mxz9
#define PORT_DPIN_30 PORT_PIN_CONSTANT(PINC, 7) // Mxz8

#define PORT_DPIN_21 PORT_PIN_CONSTANT(PIND, 0) // Screen SCL
#define PORT_DPIN_20 PORT_PIN_CONSTANT(PIND, 1) // Screen SDA
#define PORT_DPIN_19 PORT_PIN_CONSTANT(PIND, 2) // NONE
#define PORT_DPIN_18 PORT_PIN_CONSTANT(PIND, 3) // Tx BP
#define PORT_DPIN_38 PORT_PIN_CONSTANT(PIND, 7) // Arp Fast

#define PORT_DPIN_0  PORT_PIN_CONSTANT(PINE, 0) // NONE
#define PORT_DPIN_1  PORT_PIN_CONSTANT(PINE, 1) // Tx Midi
#define PORT_DPIN_5  PORT_PIN_CONSTANT(PINE, 3) // NONE
#define PORT_DPIN_2  PORT_PIN_CONSTANT(PINE, 4) // LED CS
#define PORT_DPIN_3  PORT_PIN_CONSTANT(PINE, 5) // LED DIN

#define PORT_DPIN_41 PORT_PIN_CONSTANT(PING, 0) // Loop1
#define PORT_DPIN_40 PORT_PIN_CONSTANT(PING, 1) // Loop3
#define PORT_DPIN_39 PORT_PIN_CONSTANT(PING, 2) // Arp Down
#define PORT_DPIN_4  PORT_PIN_CONSTANT(PING, 5) // LED CLK

#define PORT_DPIN_17 PORT_PIN_CONSTANT(PINH, 0) // NONE
#define PORT_DPIN_16 PORT_PIN_CONSTANT(PINH, 1) // NONE
#define PORT_DPIN_6  PORT_PIN_CONSTANT(PINH, 3) // NONE
#define PORT_DPIN_7  PORT_PIN_CONSTANT(PINH, 4) // NONE
#define PORT_DPIN_8  PORT_PIN_CONSTANT(PINH, 5) // NONE
#define PORT_DPIN_9  PORT_PIN_CONSTANT(PINH, 6) // NONE
 
#define PORT_DPIN_15 PORT_PIN_CONSTANT(PINJ, 0) // NONE
#define PORT_DPIN_14 PORT_PIN_CONSTANT(PINJ, 1) // NONE

#define PORT_DPIN_49 PORT_PIN_CONSTANT(PINL, 0) // Arp S2
#define PORT_DPIN_48 PORT_PIN_CONSTANT(PINL, 1) // Arp Hold
#define PORT_DPIN_47 PORT_PIN_CONSTANT(PINL, 2) // Arp Up
#define PORT_DPIN_46 PORT_PIN_CONSTANT(PINL, 3) // Arp Slow
#define PORT_DPIN_45 PORT_PIN_CONSTANT(PINL, 4) // Metronome
#define PORT_DPIN_44 PORT_PIN_CONSTANT(PINL, 5) // Loop2
#define PORT_DPIN_43 PORT_PIN_CONSTANT(PINL, 6) // Loop4
#define PORT_DPIN_42 PORT_PIN_CONSTANT(PINL, 7) // Arp Spec

#endif // PORT_MAP_H